# Generated by Django 5.1 on 2024-08-09 13:22

import django.db.models.functions.datetime
import utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncasariModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma_in_ron', models.FloatField(blank=True, null=True)),
                ('suma', models.FloatField()),
                ('valuta', models.CharField(choices=[('RON', 'RON'), ('USD', 'USD'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('CHF', 'CHF'), ('AED', 'AED'), ('AUD', 'AUD'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('CNY', 'CNY'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('EGP', 'EGP'), ('EUR', 'EUR'), ('HUF', 'HUF'), ('INR', 'INR'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('MDL', 'MDL'), ('MXN', 'MXN'), ('NOK', 'NOK'), ('NZD', 'NZD'), ('PLN', 'PLN'), ('RSD', 'RSD'), ('RUB', 'RUB'), ('SEK', 'SEK'), ('THB', 'THB'), ('TRY', 'TRY'), ('UAH', 'UAH'), ('XAU', 'XAU'), ('XDR', 'XDR'), ('ZAR', 'ZAR')], default='RON', max_length=3)),
                ('tip_tranzactie', models.CharField(choices=[('BANCAR', 'BANCAR'), ('NUMERAR', 'NUMERAR')], default='BANCAR', max_length=7)),
                ('data_incasarii', models.DateField(blank=True, null=True)),
                ('fisier', models.FileField(upload_to=utils.files.get_save_path)),
                ('actualizat_la', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name_plural': 'Incasari',
            },
        ),
    ]
