# Generated by Django 5.1 on 2024-08-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incasari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incasarimodel',
            name='sursa_venit',
            field=models.CharField(choices=[('Venit din activitati independente', 'Venit din activitati independente'), ('Venit din alte surse', 'Venit din alte surse'), ('Venit din cedarea folosintei bunurilor', 'Venit din cedarea folosintei bunurilor'), ('Venit si/sau castig din investitii', 'Venit si/sau castig din investitii'), ('Venit din drepturi de proprietate intelectuala', 'Venit din drepturi de proprietate intelectuala'), ('Venit din activitati agricole, silvicultura si piscicultura', 'Venit din activitati agricole, silvicultura si piscicultura'), ('Venit distribuit din asociere cu persoane juridice, contribuabili potrivit prevederilor titlului II, titlului III sau Legii nr.170/2016', 'Venit distribuit din asociere cu persoane juridice, contribuabili potrivit prevederilor titlului II, titlului III sau Legii nr.170/2016')], default='Venit din activitati independente', max_length=300),
        ),
    ]
