# Generated by Django 5.1 on 2024-08-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incasari', '0002_incasarimodel_sursa_venit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incasarimodel',
            name='tip_tranzactie',
            field=models.CharField(choices=[('BANCAR', '💳 BANCAR'), ('NUMERAR', '💵 NUMERAR')], default='BANCAR', max_length=7),
        ),
    ]
