# Generated by Django 5.1 on 2024-08-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incasari', '0004_alter_incasarimodel_valuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incasarimodel',
            name='valuta',
            field=models.CharField(choices=[('RON', '🇷🇴 RON - Romania'), ('USD', '🇺🇸 USD - USA'), ('GBP', '🇬🇧 GBP - UK'), ('CAD', '🇨🇦 CAD - Canada'), ('EUR', '🇪🇺 EUR - European Union Zone'), ('CHF', '🇨🇭 CHF - Switzerland'), ('AED', '🇦🇪 AED - UAE'), ('AUD', '🇦🇺 AUD - Australia'), ('BGN', '🇧🇬 BGN - Bulgaria'), ('BRL', '🇧🇷 BRL - Brazil'), ('CNY', '🇨🇳 CNY - China'), ('CZK', '🇨🇿 CZK - Czech Republic'), ('DKK', '🇩🇰 DKK - Denmark'), ('EGP', '🇪🇬 EGP - Egypt'), ('HUF', '🇭🇺 HUF - Hungary'), ('INR', '🇮🇳 INR - India'), ('JPY', '🇯🇵 JPY - Japan'), ('KRW', '🇰🇷 KRW - South Korea'), ('MDL', '🇲🇩 MDL - Moldova'), ('MXN', '🇲🇽 MXN - Mexico'), ('NOK', '🇳🇴 NOK - Norway'), ('NZD', '🇳🇿 NZD - New Zealand'), ('PLN', '🇵🇱 PLN - Poland'), ('RSD', '🇷🇸 RSD - Serbia'), ('RUB', '🇷🇺 RUB - Russia'), ('SEK', '🇸🇪 SEK - Sweden'), ('THB', '🇹🇭 THB - Thailand'), ('TRY', '🇹🇷 TRY - Turkey'), ('UAH', '🇺🇦 UAH - Ukraine'), ('XAU', '🏅 XAU - Gold'), ('XDR', '🌐 XDR - IMF Special Drawing Rights'), ('ZAR', '🇿🇦 ZAR - South Africa')], default='RON', max_length=3),
        ),
    ]
