# Generated by Django 5.1 on 2024-08-09 07:13

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetariModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('adresa', models.CharField(max_length=500)),
                ('nr_reg_com', models.CharField(max_length=50)),
                ('cif_vat_cui', models.CharField(max_length=20)),
                ('telefon', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('iban', models.CharField(max_length=34)),
                ('caen_principal', models.CharField(max_length=4)),
                ('caen_secondar_1', models.CharField(default='', max_length=4)),
                ('caen_secondar_2', models.CharField(default='', max_length=4)),
                ('caen_secondar_3', models.CharField(default='', max_length=4)),
                ('caen_secondar_4', models.CharField(default='', max_length=4)),
                ('caen_secondar_5', models.CharField(default='', max_length=4)),
                ('actualizat_la', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'verbose_name_plural': 'Setari',
            },
        ),
        migrations.DeleteModel(
            name='Setari',
        ),
    ]
