# Generated by Django 5.1 on 2024-08-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setari', '0002_setarimodel_delete_setari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setarimodel',
            name='caen_secondar_1',
            field=models.CharField(default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='setarimodel',
            name='caen_secondar_2',
            field=models.CharField(default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='setarimodel',
            name='caen_secondar_3',
            field=models.CharField(default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='setarimodel',
            name='caen_secondar_4',
            field=models.CharField(default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='setarimodel',
            name='caen_secondar_5',
            field=models.CharField(default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='setarimodel',
            name='iban',
            field=models.CharField(max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='setarimodel',
            name='telefon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
