# Generated by Django 5.1 on 2024-08-09 10:44

import setari.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setari', '0004_alter_setarimodel_caen_secondar_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setarimodel',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[setari.models.validate_iban_length]),
        ),
    ]
